### ISSUE TITLE
angular.js:13708 Error: [$compile:ctreq] Controller 'mdTable', required by directive 'mdRow', can't be found!

### ISSUE THREAD

**Issue by mo0feng** [daniel-nagy/fixed-table-header#19]
``````
```html
    <div ng-repeat="tab in tabs"  flex="{{ tab.width }}">
        <md-table-container >
            <div style="overflow: auto; max-height: 300px;" ng-table-height>
                 <table md-table multiple md-progress="tab.promise" >
                    <thead md-head md-order="tab.query.order"  md-on-reorder="logOrder" fiex>
                        <tr md-row>
                            <th md-column  ng-repeat="obj in tab.source|filter:{if_visible:true}" md-order-by="{{ obj.row_name }}" md-tabindex="$parent.$index">
                                <span>{{ obj.show_name }}</span>
                            </th>
                        </tr>
                    </thead>
                    <tbody md-body>
                        <tr md-row ng-repeat="dessert in tab.desserts.data">
                            <td md-cell ng-repeat="val in dessert track by $index" ng-class="{'headcol':$first}">
                                {{ val }}
                                <md-tooltip>
                                    {{ dessert[0] }}
                                </md-tooltip>
                            </td>
                        </tr>
                    </tbody>
                 </table>
            </div>
        </md-table-container >
    </div>
```
``````

angular.js:13708 Error: [$compile:ctreq] Controller 'mdTable', required by directive 'mdRow', can't be found!
http://errors.angularjs.org/1.5.7/$compile/ctreq?p0=mdTable&p1=mdRow
Error: [$compile:ctreq] Controller 'mdTable', required by directive 'mdColumn', can't be found!
http://errors.angularjs.org/1.5.7/$compile/ctreq?p0=mdTable&p1=mdColumn
    at angular.js:68
    at getControllers (angular.js:9296)
    at getControllers (angular.js:9303)
    at nodeLinkFn (angular.js:9219)
    at compositeLinkFn (angular.js:8510)
    at publicLinkFn (angular.js:8390)
    at lazyCompilation (angular.js:8728)
    at boundTranscludeFn (angular.js:8527)
    at controllersBoundTransclude (angular.js:9265)
    at ngRepeatAction (angular.js:29607)

angular.js:13708 TypeError: Cannot read property 'parent' of undefined
    at Object.enter (angular.js:5446)
    at ngRepeatTransclude (angular.js:29613)
    at publicLinkFn (angular.js:8389)
    at lazyCompilation (angular.js:8728)
    at boundTranscludeFn (angular.js:8527)
    at controllersBoundTransclude (angular.js:9265)
    at ngRepeatAction (angular.js:29607)
    at $watchCollectionAction (angular.js:17147)
    at Scope.$digest (angular.js:17286)
    at Scope.$apply (angular.js:17552)

**Comment by panickerr** [comment]
Im getting similar error : 
`angular.js:13550 Error: [$compile:ctreq] Controller 'mdTable', required by directive 'mdColumn', can't be found!
http://errors.angularjs.org/1.5.5/$compile/ctreq?p0=mdTable&p1=mdColumn
    at http://localhost:3000/bower_components/angular/angular.js:68:12
    at getControllers (http://localhost:3000/bower_components/angular/angular.js:9174:17)
    at getControllers (http://localhost:3000/bower_components/angular/angular.js:9181:22)
    at nodeLinkFn (http://localhost:3000/bower_components/angular/angular.js:9097:33)
    at compositeLinkFn (http://localhost:3000/bower_components/angular/angular.js:8397:13)
    at nodeLinkFn (http://localhost:3000/bower_components/angular/angular.js:9088:24)
    at compositeLinkFn (http://localhost:3000/bower_components/angular/angular.js:8397:13)
    at nodeLinkFn (http://localhost:3000/bower_components/angular/angular.js:9088:24)
    at compositeLinkFn (http://localhost:3000/bower_components/angular/angular.js:8397:13)
    at publicLinkFn (http://localhost:3000/bower_components/angular/angular.js:8277:30) <thead fix-head="" md-head="" md-order="vm.query.order" md-on-reorder="vm.getUsers" class="md-head ng-isolate-scope" style="visibility: hidden;">`

**Comment by panickerr** [comment]
@mo0feng you can refer to [https://github.com/daniel-nagy/fixed-table-header/issues/12](Issue 12 which has a discussion on this topic) to get a basic idea on what is happening and what is not. Anyways even after that my problem was not solved.

**Comment by mo0feng** [comment]
@panickerr Thank you, I use the angular - datatables solved.

**Comment by Sayaren** [comment]
use ng-show instead ng-if
